### ISSUE TITLE
App not working in Heroku

### ISSUE THREAD

**Issue by beesman** [Snyk/pkgbot#5]
Hi,

When building in Heroku I get an application error & see this in the logfile: 
`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
`
I would expect the app host & port to be defined somewhere, but don't see this.

Can you advise?
Thanks

**Comment by adrukh** [comment]
@beesman apologies, we were missing a `Procfile` to specify a worker dyno. Fixed with https://github.com/snyk/pkgbot/pull/6

Note that `pkgbot` communicates with a slack token. It does not require serve requests as a web server, so no `host` or `port` are needed.

You can generate a slack API token for your bot [here](https://api.slack.com/custom-integrations). Make sure to sign up with [Snyk](https://snyk.io) and use your Snyk token too so you can test packages for vulnerabilities!

**Comment by beesman** [comment]
Thanks @adrukh but still not working for me. Looking in the log I see  `Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`. The process state is the changed from started to crashed.

**Comment by adrukh** [comment]
@beesman you seem to be using a `Procfile`-less commit? This makes heroku assume this is a web application, but this is not.

Please run
`git pull origin master` and make sure you are on git sha `f64d60b`
Then run
`git push heroku master` to update your deployment. Don't forget to set the two env vars I mentioned above!

**Comment by beesman** [comment]
Maybe I'm being stupid or have missed something, but I can see that I've deployed revision `f64d60b` with `Procfile`, I have the two env vars configured, and yet I still see `Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`.

**Comment by adrukh** [comment]
@beesman please don't take ownership of stupidity, I have my moments as well.

1. Try the `Deploy to Heroku` button on https://github.com/snyk/pkgbot#the-quick-way and tell me if it works for you.

2. Are you getting this error in `git push heroku master` or in `heroku logs`?

**Comment by karenyavine** [comment]
Hey @beesman! 
Did everything work out? Anything I can help with?

**Comment by beesman** [comment]
Hi @karenyavine still no joy I'm afraid. I tried a clean deploy using the `Deploy to Heroku` button as suggested by @adrukh but still see the same error in heroku logs.

**Comment by karenyavine** [comment]
Hey @beesman!
Found out what was the issue. Could you take the lastest version of pkgbot (`8f733ba`) and use the deploy to heroku button?
Once deployed, verify that under Resources, web is toggled off and worker is on.
